package export

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"time"

	"lingo/model"
)

func escapeLaTeX(s string) string {
	replacer := strings.NewReplacer(
		`\`, `\textbackslash{}`,
		`{`, `\{`,
		`}`, `\}`,
		`$`, `\$`,
		`&`, `\&`,
		`#`, `\#`,
		`^`, `\^{}`,
		`_`, `\_`,
		`~`, `\textasciitilde{}`,
		`%`, `\%`,
	)
	return replacer.Replace(s)
}

func formatDate(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.Format("2006-01-02")
}

func wordRow(w model.Word) string {
	defs := []string{}
	for _, d := range w.ECDictDefs {
		defs = append(defs, fmt.Sprintf(`[%s] %s`, escapeLaTeX(d.Pos), escapeLaTeX(d.Meaning)))
	}
	for _, d := range w.Definitions {
		defs = append(defs, fmt.Sprintf(`[%s] %s`, escapeLaTeX(d.Pos), escapeLaTeX(d.Meaning)))
	}
	def := strings.Join(defs, `; `)
	if def == "" {
		def = "---"
	}
	phonetic := w.Phonetic
	if phonetic == "" {
		phonetic = "---"
	}
	tags := escapeLaTeX(strings.Join(w.Tags, ", "))
	return fmt.Sprintf(`%s & %s & %s & %s \\`,
		escapeLaTeX(w.Word), phonetic, def, tags)
}

// WordListData holds all data for the word list template.
type WordListData struct {
	Words     []model.Word
	TagFilter string
}

// GenerateWordsTeX renders a word list as a LaTeX longtable document.
func GenerateWordsTeX(words []model.Word, tagFilter string) (string, error) {
	tmpl := template.Must(template.New("words").Funcs(template.FuncMap{
		"escape":  escapeLaTeX,
		"join":    strings.Join,
		"wordRow": wordRow,
	}).Parse(`\documentclass[12pt,a4paper]{ctexart}
\usepackage{longtable,booktabs,geometry}
\geometry{margin=2cm}
\usepackage[colorlinks=true,linkcolor=black]{hyperref}

\title{Word List{{if .TagFilter}}: {{.TagFilter}}{{end}} }
\date{\today}
\author{Generated by Lingo}

\begin{document}
\maketitle

\setlength{\tabcolsep}{6pt}
\begin{longtable}{p{4.5cm}p{3.5cm}p{6cm}p{2.5cm}}
\toprule
\textbf{Word} & \textbf{Phonetic} & \textbf{Definition} & \textbf{Tags} \\
\midrule
\endhead
\midrule
\multicolumn{4}{r}{\footnotesize Continued on next page}\\
\endfoot
\bottomrule
\endlastfoot
{{range .Words}}
{{wordRow .}}{{end}}
\end{longtable}
\end{document}
`))

	var buf bytes.Buffer
	err := tmpl.Execute(&buf, WordListData{Words: words, TagFilter: tagFilter})
	if err != nil {
		return "", fmt.Errorf("render words tex: %w", err)
	}
	return buf.String(), nil
}

var articleTemplate = template.Must(template.New("article").Funcs(template.FuncMap{
	"escape":     escapeLaTeX,
	"join":       strings.Join,
	"formatDate": formatDate,
}).Parse(`\documentclass[12pt,a4paper]{ctexart}
\usepackage{geometry,fancyhdr,tcolorbox,xcolor}
\geometry{margin=2.5cm}
\usepackage[colorlinks=true,linkcolor=black]{hyperref}

\definecolor{lightgray}{RGB}{245,245,245}
\definecolor{accent}{RGB}{65,105,225}

\title{ {{.Title}} }
{{if .Author}}\author{ {{.Author}} }{{end}}
\date{ {{.Date}} }

\begin{document}
\maketitle

{{if .Summary}}
\begin{tcolorbox}[colback=lightgray,arc=4mm,boxrule=0mm]
\textbf{Summary}\smallskip

{{.Summary}}
\end{tcolorbox}
{{end}}

{{if .Source}}
\textit{Source: {{.Source}}{{if .SourceURL}} --- \url{ {{ .SourceURL }} }{{end}} }
\bigskip
{{end}}

{{.Content}}

{{if .Tags}}
\vspace{1em}
\textbf{Tags:} {{.Tags}}
{{end}}

{{if .AIAnalysis}}
\section*{AI Analysis}

{{if .AIAnalysis.Summary}}
\begin{tcolorbox}[colback=lightgray,arc=4mm,boxrule=0mm]
{{.AIAnalysis.Summary}}
\end{tcolorbox}
{{end}}

{{if .AIAnalysis.Words}}
\subsection*{Vocabulary ({{len .AIAnalysis.Words}} words)}
\begin{itemize}
{{range .AIAnalysis.Words}}
  \item \textbf{ {{.Word}} }{{if .Definitions}} --- {{range $i, $d := .Definitions}}{{if $i}}; {{end}}[{{$d.Pos}}] {{$d.Meaning}}{{end}}{{end}}
  {{if .Example}}\\ \textit{e.g.} {{.Example}}{{end}}
{{end}}
\end{itemize}
{{end}}

{{if .AIAnalysis.Phrases}}
\subsection*{Phrases ({{len .AIAnalysis.Phrases}})}
\begin{itemize}
{{range .AIAnalysis.Phrases}}
  \item \textbf{ {{.Phrase}} } [{{.Type}}] --- {{.Definition}}
  {{if .Example}}\\ \textit{e.g.} {{.Example}}{{end}}
{{end}}
\end{itemize}
{{end}}

{{if .AIAnalysis.Sentences}}
\subsection*{Sentences ({{len .AIAnalysis.Sentences}})}
\begin{itemize}
{{range .AIAnalysis.Sentences}}
  \item {{.Text}}
  {{if .Translation}}\\ \textit{Translation:} {{.Translation}}{{end}}
  {{if .Why}}\\ \textit{Why:} {{.Why}}{{end}}
{{end}}
\end{itemize}
{{end}}
{{end}}
\end{document}
`))

// ArticleData holds data for the article LaTeX template.
type ArticleData struct {
	Title      string
	Author     string
	Date       string
	Source     string
	SourceURL  string
	Content    string
	Summary    string
	Tags       string
	AIAnalysis *model.AIAnalysis
}

// GenerateArticleTeX renders a single article as a LaTeX document.
func GenerateArticleTeX(a model.Article) (string, error) {
	data := ArticleData{
		Title:     escapeLaTeX(a.Title),
		Author:    escapeLaTeX(a.Author),
		Date:      formatDate(a.CreatedAt),
		Source:    escapeLaTeX(a.Source),
		SourceURL: a.SourceURL,
		Content:   a.Content,
		Summary:   a.Summary,
		Tags:      escapeLaTeX(strings.Join(a.Tags, ", ")),
	}

	if a.AIAnalysis != nil {
		data.AIAnalysis = cleanAnalysis(a.AIAnalysis)
	}

	var buf bytes.Buffer
	err := articleTemplate.Execute(&buf, data)
	if err != nil {
		return "", fmt.Errorf("render article tex: %w", err)
	}
	return buf.String(), nil
}

var compositionTemplate = template.Must(template.New("composition").Funcs(template.FuncMap{
	"escape":     escapeLaTeX,
	"join":       strings.Join,
	"formatDate": formatDate,
}).Parse(`\documentclass[12pt,a4paper]{ctexart}
\usepackage{geometry,fancyhdr,tcolorbox,xcolor}
\geometry{margin=2.5cm}
\usepackage[colorlinks=true,linkcolor=black]{hyperref}

\definecolor{lightgray}{RGB}{245,245,245}
\definecolor{lightred}{RGB}{255,240,240}
\definecolor{lightgreen}{RGB}{240,255,240}

\title{ {{.Title}} }
{{if .Author}}\author{ {{.Author}} }{{end}}
\date{ {{.Date}} }

\begin{document}
\maketitle

{{if .Topic}}
\textbf{Topic:} {{.Topic}}
\bigskip
{{end}}

{{.Content}}

{{if .Tags}}
\vspace{1em}
\textbf{Tags:} {{.Tags}}
{{end}}

{{if .Notes}}
\vspace{1em}
\textit{Notes:} {{.Notes}}
{{end}}

{{if .AIAnalysis}}
\newpage
\section*{AI Analysis}

{{if .AIAnalysis.Summary}}
\begin{tcolorbox}[colback=lightgray,arc=4mm,boxrule=0mm]
\textbf{Summary}\smallskip

{{.AIAnalysis.Summary}}
\end{tcolorbox}
{{end}}

{{if .AIAnalysis.GrammarErrors}}
\subsection*{Grammar \& Language Errors ({{len .AIAnalysis.GrammarErrors}})}
{{range .AIAnalysis.GrammarErrors}}
\begin{tcolorbox}[colback=lightred,arc=2mm,boxrule=0mm,left=2mm]
\textbf{[{{.ErrorType}}]} \textbf{Original:} {{.Sentence}}

\textbf{Correction:} {{.Correction}}
{{if .Explanation}}
\textit{Explanation:} {{.Explanation}}
{{end}}
\end{tcolorbox}
\medskip
{{end}}
{{end}}

{{if .AIAnalysis.Words}}
\subsection*{Vocabulary ({{len .AIAnalysis.Words}} words)}
\begin{itemize}
{{range .AIAnalysis.Words}}
  \item \textbf{ {{.Word}} }{{if .Definitions}} --- {{range $i, $d := .Definitions}}{{if $i}}; {{end}}[{{$d.Pos}}] {{$d.Meaning}}{{end}}{{end}}
  {{if .Example}}\\ \textit{e.g.} {{.Example}}{{end}}
{{end}}
\end{itemize}
{{end}}

{{if .AIAnalysis.Phrases}}
\subsection*{Phrases ({{len .AIAnalysis.Phrases}})}
\begin{itemize}
{{range .AIAnalysis.Phrases}}
  \item \textbf{ {{.Phrase}} } [{{.Type}}] --- {{.Definition}}
  {{if .Example}}\\ \textit{e.g.} {{.Example}}{{end}}
{{end}}
\end{itemize}
{{end}}

{{if .AIAnalysis.Sentences}}
\subsection*{Notable Sentences ({{len .AIAnalysis.Sentences}})}
\begin{itemize}
{{range .AIAnalysis.Sentences}}
  \item {{.Text}}
  {{if .Translation}}\\ \textit{Translation:} {{.Translation}}{{end}}
  {{if .Why}}\\ \textit{Why:} {{.Why}}{{end}}
{{end}}
\end{itemize}
{{end}}

{{if .AIAnalysis.ModelEssay}}
\subsection*{Model Essay (范文)}
\begin{tcolorbox}[colback=lightgreen,arc=2mm,boxrule=0mm]
{{.AIAnalysis.ModelEssay}}
\end{tcolorbox}
{{end}}

{{if .AIAnalysis.ModelEssay2}}
\newpage
\section*{Model Essay 2 (范文二)}
\begin{tcolorbox}[colback=lightgreen,arc=2mm,boxrule=0mm]
{{.AIAnalysis.ModelEssay2.Essay}}
\end{tcolorbox}

{{if .AIAnalysis.ModelEssay2.Words}}
\subsection*{Model Essay 2 Vocabulary}
\begin{itemize}
{{range .AIAnalysis.ModelEssay2.Words}}
  \item \textbf{ {{.Word}} }{{if .Definitions}} --- {{range $i, $d := .Definitions}}{{if $i}}; {{end}}[{{$d.Pos}}] {{$d.Meaning}}{{end}}{{end}}
{{end}}
\end{itemize}
{{end}}
{{end}}
{{end}}
\end{document}
`))

// CompositionData holds data for the composition LaTeX template.
type CompositionData struct {
	Title      string
	Author     string
	Date       string
	Topic      string
	Content    string
	Tags       string
	Notes      string
	AIAnalysis *model.AIAnalysis
}

// GenerateCompositionTeX renders a single composition as a LaTeX document.
func GenerateCompositionTeX(c model.Composition) (string, error) {
	data := CompositionData{
		Title:  escapeLaTeX(c.Title),
		Author: escapeLaTeX(c.Author),
		Date:   formatDate(c.CreatedAt),
		Topic:  escapeLaTeX(c.Topic),
		Tags:   escapeLaTeX(strings.Join(c.Tags, ", ")),
		Notes:  c.Notes,
	}

	// Content is markdown; preserve it as-is (LaTeX will render it as plain text).
	data.Content = c.Content

	if c.AIAnalysis != nil {
		data.AIAnalysis = cleanAnalysis(c.AIAnalysis)
	}

	var buf bytes.Buffer
	err := compositionTemplate.Execute(&buf, data)
	if err != nil {
		return "", fmt.Errorf("render composition tex: %w", err)
	}
	return buf.String(), nil
}

// cleanAnalysis returns a copy of the AI analysis with escaped text fields.
func cleanAnalysis(a *model.AIAnalysis) *model.AIAnalysis {
	if a == nil {
		return nil
	}
	out := *a

	out.Summary = a.Summary // pass through, LaTeX-compatible
	for i := range out.Words {
		out.Words[i].Word = escapeLaTeX(out.Words[i].Word)
		out.Words[i].Example = escapeLaTeX(out.Words[i].Example)
		out.Words[i].Notes = escapeLaTeX(out.Words[i].Notes)
		for j := range out.Words[i].Definitions {
			out.Words[i].Definitions[j].Pos = escapeLaTeX(out.Words[i].Definitions[j].Pos)
			out.Words[i].Definitions[j].Meaning = escapeLaTeX(out.Words[i].Definitions[j].Meaning)
		}
	}
	for i := range out.Phrases {
		out.Phrases[i].Phrase = escapeLaTeX(out.Phrases[i].Phrase)
		out.Phrases[i].Type = escapeLaTeX(out.Phrases[i].Type)
		out.Phrases[i].Definition = escapeLaTeX(out.Phrases[i].Definition)
		out.Phrases[i].Example = escapeLaTeX(out.Phrases[i].Example)
	}
	for i := range out.Sentences {
		out.Sentences[i].Text = escapeLaTeX(out.Sentences[i].Text)
		out.Sentences[i].Translation = escapeLaTeX(out.Sentences[i].Translation)
		out.Sentences[i].Why = escapeLaTeX(out.Sentences[i].Why)
	}
	for i := range out.GrammarErrors {
		out.GrammarErrors[i].Sentence = escapeLaTeX(out.GrammarErrors[i].Sentence)
		out.GrammarErrors[i].Correction = escapeLaTeX(out.GrammarErrors[i].Correction)
		out.GrammarErrors[i].Explanation = escapeLaTeX(out.GrammarErrors[i].Explanation)
		out.GrammarErrors[i].ErrorType = escapeLaTeX(out.GrammarErrors[i].ErrorType)
	}
	if out.ModelEssay2 != nil {
		for i := range out.ModelEssay2.Words {
			out.ModelEssay2.Words[i].Word = escapeLaTeX(out.ModelEssay2.Words[i].Word)
		}
	}

	return &out
}

var multiArticleTemplate = template.Must(template.New("multiArticle").Funcs(template.FuncMap{
	"escape":     escapeLaTeX,
	"formatDate": formatDate,
}).Parse(`\documentclass[12pt,a4paper]{ctexart}
\usepackage{geometry,fancyhdr,tcolorbox,xcolor}
\geometry{margin=2.5cm}
\usepackage[colorlinks=true,linkcolor=black]{hyperref}

\definecolor{lightgray}{RGB}{245,245,245}

\title{Articles Export{{if .TagFilter}}: {{.TagFilter}}{{end}} }
\date{\today}
\author{Generated by Lingo}

\begin{document}
\maketitle
{{range $i, $a := .Articles}}
{{if $i}}\newpage{{end}}

\section*{ {{.Title}} }
{{if .Author}}\textbf{Author:} {{.Author}}\smallskip{{end}}
{{if .Date}}\textbf{Date:} {{.Date}}\smallskip{{end}}

{{if .Summary}}
\begin{tcolorbox}[colback=lightgray,arc=4mm,boxrule=0mm]
{{.Summary}}
\end{tcolorbox}
{{end}}

{{.Content}}

{{if .Tags}}\textbf{Tags:} {{.Tags}}{{end}}

{{if .AIAnalysis}}
\subsection*{AI Analysis}
{{if .AIAnalysis.Summary}}
\begin{tcolorbox}[colback=lightgray,arc=4mm,boxrule=0mm]
{{.AIAnalysis.Summary}}
\end{tcolorbox}
{{end}}
{{if .AIAnalysis.Words}}
\subsubsection*{Vocabulary}
\begin{itemize}
{{range .AIAnalysis.Words}}
  \item \textbf{ {{.Word}} }{{if .Definitions}} --- {{range $j, $d := .Definitions}}{{if $j}}; {{end}}[{{$d.Pos}}] {{$d.Meaning}}{{end}}{{end}}
{{end}}
\end{itemize}
{{end}}
{{end}}
{{end}}
\end{document}
`))

// ArticlesExportData holds data for the multi-article LaTeX template.
type ArticlesExportData struct {
	Articles  []ArticleData
	TagFilter string
}

// GenerateArticlesTeX renders multiple articles as a single LaTeX document.
func GenerateArticlesTeX(articles []model.Article, tagFilter string) (string, error) {
	var items []ArticleData
	for _, a := range articles {
		item := ArticleData{
			Title:   escapeLaTeX(a.Title),
			Author:  escapeLaTeX(a.Author),
			Date:    formatDate(a.CreatedAt),
			Content: a.Content,
			Summary: a.Summary,
			Tags:    escapeLaTeX(strings.Join(a.Tags, ", ")),
		}
		if a.AIAnalysis != nil {
			item.AIAnalysis = cleanAnalysis(a.AIAnalysis)
		}
		items = append(items, item)
	}

	var buf bytes.Buffer
	err := multiArticleTemplate.Execute(&buf, ArticlesExportData{Articles: items, TagFilter: tagFilter})
	if err != nil {
		return "", fmt.Errorf("render articles tex: %w", err)
	}
	return buf.String(), nil
}

var multiCompositionTemplate = template.Must(template.New("multiComposition").Funcs(template.FuncMap{
	"escape":     escapeLaTeX,
	"formatDate": formatDate,
}).Parse(`\documentclass[12pt,a4paper]{ctexart}
\usepackage{geometry,fancyhdr,tcolorbox,xcolor}
\geometry{margin=2.5cm}
\usepackage[colorlinks=true,linkcolor=black]{hyperref}

\definecolor{lightgray}{RGB}{245,245,245}
\definecolor{lightred}{RGB}{255,240,240}
\definecolor{lightgreen}{RGB}{240,255,240}

\title{Compositions Export{{if .TagFilter}}: {{.TagFilter}}{{end}} }
\date{\today}
\author{Generated by Lingo}

\begin{document}
\maketitle
{{range $i, $c := .Compositions}}
{{if $i}}\newpage{{end}}

\section*{ {{.Title}} }
{{if .Author}}\textbf{Author:} {{.Author}}\smallskip{{end}}
{{if .Date}}\textbf{Date:} {{.Date}}\smallskip{{end}}
{{if .Topic}}\textbf{Topic:} {{.Topic}}\smallskip{{end}}

{{.Content}}

{{if .Tags}}\textbf{Tags:} {{.Tags}}{{end}}
{{if .Notes}}\textit{Notes:} {{.Notes}}{{end}}

{{if .AIAnalysis}}
\subsection*{AI Analysis}
{{if .AIAnalysis.Summary}}
\begin{tcolorbox}[colback=lightgray,arc=4mm,boxrule=0mm]
{{.AIAnalysis.Summary}}
\end{tcolorbox}
{{end}}
{{if .AIAnalysis.GrammarErrors}}
\subsubsection*{Grammar \& Language Errors}
{{range .AIAnalysis.GrammarErrors}}
\begin{tcolorbox}[colback=lightred,arc=2mm,boxrule=0mm,left=2mm]
\textbf{[{{.ErrorType}}]} {{.Sentence}} $\rightarrow$ {{.Correction}}
{{if .Explanation}}\\ \textit{Explanation:} {{.Explanation}}{{end}}
\end{tcolorbox}
\medskip
{{end}}
{{end}}
{{if .AIAnalysis.Words}}
\subsubsection*{Vocabulary}
\begin{itemize}
{{range .AIAnalysis.Words}}
  \item \textbf{ {{.Word}} }{{if .Definitions}} --- {{range $j, $d := .Definitions}}{{if $j}}; {{end}}[{{$d.Pos}}] {{$d.Meaning}}{{end}}{{end}}
{{end}}
\end{itemize}
{{end}}
{{if .AIAnalysis.Phrases}}
\subsubsection*{Phrases}
\begin{itemize}
{{range .AIAnalysis.Phrases}}
  \item \textbf{ {{.Phrase}} } [{{.Type}}] --- {{.Definition}}
{{end}}
\end{itemize}
{{end}}
{{end}}
{{end}}
\end{document}
`))

// CompositionsExportData holds data for the multi-composition LaTeX template.
type CompositionsExportData struct {
	Compositions []CompositionData
	TagFilter    string
}

// GenerateCompositionsTeX renders multiple compositions as a single LaTeX document.
func GenerateCompositionsTeX(comps []model.Composition, tagFilter string) (string, error) {
	var items []CompositionData
	for _, c := range comps {
		item := CompositionData{
			Title:   escapeLaTeX(c.Title),
			Author:  escapeLaTeX(c.Author),
			Date:    formatDate(c.CreatedAt),
			Topic:   escapeLaTeX(c.Topic),
			Content: c.Content,
			Tags:    escapeLaTeX(strings.Join(c.Tags, ", ")),
			Notes:   c.Notes,
		}
		if c.AIAnalysis != nil {
			item.AIAnalysis = cleanAnalysis(c.AIAnalysis)
		}
		items = append(items, item)
	}

	var buf bytes.Buffer
	err := multiCompositionTemplate.Execute(&buf, CompositionsExportData{Compositions: items, TagFilter: tagFilter})
	if err != nil {
		return "", fmt.Errorf("render compositions tex: %w", err)
	}
	return buf.String(), nil
}
